// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(SkiCenterDbContext))]
    [Migration("20261005160743_RefactoredToFitGivenDataStructure")]
    partial class RefactoredToFitGivenDataStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingMeetingRoom", b =>
                {
                    b.Property<int>("BookingsBookingID")
                        .HasColumnType("int");

                    b.Property<int>("MeetingRoomsMeetingRoomID")
                        .HasColumnType("int");

                    b.HasKey("BookingsBookingID", "MeetingRoomsMeetingRoomID");

                    b.HasIndex("MeetingRoomsMeetingRoomID");

                    b.ToTable("BookingMeetingRoom");
                });

            modelBuilder.Entity("EntityLayer.Accommodation", b =>
                {
                    b.Property<int>("AccommodationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccommodationID"));

                    b.Property<string>("AccommodationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccommodationTypeID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AccommodationID");

                    b.HasIndex("AccommodationTypeID");

                    b.ToTable("Accommodations");
                });

            modelBuilder.Entity("EntityLayer.AccommodationType", b =>
                {
                    b.Property<int>("AccommodationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccommodationTypeID"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfBeds")
                        .HasColumnType("int");

                    b.HasKey("AccommodationTypeID");

                    b.ToTable("AccommodationType");
                });

            modelBuilder.Entity("EntityLayer.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool>("HasCancellationInsurance")
                        .HasColumnType("bit");

                    b.Property<int?>("StaffID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BookingID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("StaffID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EntityLayer.BookingAccommodation", b =>
                {
                    b.Property<int>("BookingAccommodationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingAccommodationID"));

                    b.Property<int>("AccommodationID")
                        .HasColumnType("int");

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingAccommodationID");

                    b.HasIndex("AccommodationID");

                    b.HasIndex("BookingID");

                    b.ToTable("BookingAccommodations");
                });

            modelBuilder.Entity("EntityLayer.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Customer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EntityLayer.Equipment", b =>
                {
                    b.Property<int>("EquipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipmentID");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("EntityLayer.EquipmentItem", b =>
                {
                    b.Property<int>("EquipmentItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentItemID"));

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int?>("RentalID")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("EquipmentItemID");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("RentalID");

                    b.ToTable("EquipmentItems");
                });

            modelBuilder.Entity("EntityLayer.EquipmentPriceMatrix", b =>
                {
                    b.Property<int>("EquipmentPriceMatrixID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentPriceMatrixID"));

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.HasKey("EquipmentPriceMatrixID");

                    b.HasIndex("EquipmentID");

                    b.ToTable("EquipmentPriceMatrix");
                });

            modelBuilder.Entity("EntityLayer.Invoice", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceID"));

                    b.Property<decimal>("AmountExcl")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountIncl")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BookingID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Moms")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvoiceID");

                    b.HasIndex("BookingID");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("EntityLayer.MeetingRoom", b =>
                {
                    b.Property<int>("MeetingRoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeetingRoomID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MeetingRoomNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MeetingRoomID");

                    b.ToTable("MeetingRooms");
                });

            modelBuilder.Entity("EntityLayer.Rental", b =>
                {
                    b.Property<int>("RentalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalID"));

                    b.Property<int?>("BookingID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Sum")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RentalID");

                    b.HasIndex("BookingID");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("EntityLayer.SeasonPrice", b =>
                {
                    b.Property<int>("SeasonPriceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeasonPriceID"));

                    b.Property<string>("AccommodationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AccommodationTypeID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("SeasonPriceID");

                    b.HasIndex("AccommodationTypeID");

                    b.ToTable("SeasonPrices");
                });

            modelBuilder.Entity("EntityLayer.SkiLesson", b =>
                {
                    b.Property<int>("SkiLessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkiLessonID"));

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.HasKey("SkiLessonID");

                    b.ToTable("SkiLessons");
                });

            modelBuilder.Entity("EntityLayer.SkiLessonBooking", b =>
                {
                    b.Property<int>("SkiLessonBookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkiLessonBookingID"));

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<int>("SkiLessonSessionID")
                        .HasColumnType("int");

                    b.HasKey("SkiLessonBookingID");

                    b.HasIndex("BookingID");

                    b.HasIndex("SkiLessonSessionID");

                    b.ToTable("SkiLessonBooking");
                });

            modelBuilder.Entity("EntityLayer.SkiLessonSession", b =>
                {
                    b.Property<int>("SkiLessonSessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkiLessonSessionID"));

                    b.Property<string>("Days")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SkiLessonID")
                        .HasColumnType("int");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("SkiLessonSessionID");

                    b.HasIndex("SkiLessonID");

                    b.ToTable("SkiLessonSession");
                });

            modelBuilder.Entity("EntityLayer.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("StaffID");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("EntityLayer.CorporateCustomer", b =>
                {
                    b.HasBaseType("EntityLayer.Customer");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("OrganisationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("CorporateCustomer");
                });

            modelBuilder.Entity("EntityLayer.PrivateCustomer", b =>
                {
                    b.HasBaseType("EntityLayer.Customer");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Customers", t =>
                        {
                            t.Property("CreditLimit")
                                .HasColumnName("PrivateCustomer_CreditLimit");
                        });

                    b.HasDiscriminator().HasValue("PrivateCustomer");
                });

            modelBuilder.Entity("BookingMeetingRoom", b =>
                {
                    b.HasOne("EntityLayer.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingsBookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.MeetingRoom", null)
                        .WithMany()
                        .HasForeignKey("MeetingRoomsMeetingRoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityLayer.Accommodation", b =>
                {
                    b.HasOne("EntityLayer.AccommodationType", "AccommodationType")
                        .WithMany("Accommodations")
                        .HasForeignKey("AccommodationTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccommodationType");
                });

            modelBuilder.Entity("EntityLayer.Booking", b =>
                {
                    b.HasOne("EntityLayer.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Staff", null)
                        .WithMany("Bookings")
                        .HasForeignKey("StaffID");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EntityLayer.BookingAccommodation", b =>
                {
                    b.HasOne("EntityLayer.Accommodation", "Accommodation")
                        .WithMany()
                        .HasForeignKey("AccommodationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Booking", "Booking")
                        .WithMany("Accommodations")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("EntityLayer.EquipmentItem", b =>
                {
                    b.HasOne("EntityLayer.Equipment", "Equipment")
                        .WithMany("EquipmentItems")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Rental", null)
                        .WithMany("EquipmentItems")
                        .HasForeignKey("RentalID");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("EntityLayer.EquipmentPriceMatrix", b =>
                {
                    b.HasOne("EntityLayer.Equipment", "Equipment")
                        .WithMany("Prices")
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("EntityLayer.Invoice", b =>
                {
                    b.HasOne("EntityLayer.Booking", null)
                        .WithMany("Invoices")
                        .HasForeignKey("BookingID");
                });

            modelBuilder.Entity("EntityLayer.Rental", b =>
                {
                    b.HasOne("EntityLayer.Booking", null)
                        .WithMany("Rentals")
                        .HasForeignKey("BookingID");
                });

            modelBuilder.Entity("EntityLayer.SeasonPrice", b =>
                {
                    b.HasOne("EntityLayer.AccommodationType", null)
                        .WithMany("SeasonPrices")
                        .HasForeignKey("AccommodationTypeID");
                });

            modelBuilder.Entity("EntityLayer.SkiLessonBooking", b =>
                {
                    b.HasOne("EntityLayer.Booking", "Booking")
                        .WithMany("SkiLessons")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.SkiLessonSession", "SkiLessonSession")
                        .WithMany("Participants")
                        .HasForeignKey("SkiLessonSessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("SkiLessonSession");
                });

            modelBuilder.Entity("EntityLayer.SkiLessonSession", b =>
                {
                    b.HasOne("EntityLayer.SkiLesson", "SkiLesson")
                        .WithMany()
                        .HasForeignKey("SkiLessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkiLesson");
                });

            modelBuilder.Entity("EntityLayer.AccommodationType", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("SeasonPrices");
                });

            modelBuilder.Entity("EntityLayer.Booking", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("Invoices");

                    b.Navigation("Rentals");

                    b.Navigation("SkiLessons");
                });

            modelBuilder.Entity("EntityLayer.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("EntityLayer.Equipment", b =>
                {
                    b.Navigation("EquipmentItems");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("EntityLayer.Rental", b =>
                {
                    b.Navigation("EquipmentItems");
                });

            modelBuilder.Entity("EntityLayer.SkiLessonSession", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("EntityLayer.Staff", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
