name: .NET Tests Only

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x' # Validates against .NET 10 and not specific version 

    - name: Create appsettings.json for database tests
      shell: bash
      run: |
        cat <<EOF > TestLayer/appsettings.json
        {
          "ConnectionStrings": {
            "DefaultConnection": "${{ secrets.DB_CONNECTION_STRING }}"
          }
        }
        EOF

    - name: Restore dependencies for test project
      run: dotnet restore TestLayer/TestLayer.csproj

    - name: Execute tests
      run: dotnet test TestLayer/TestLayer.csproj --configuration Release --verbosity normal
